In [1]:
import torch
import numpy as np

In [2]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)

In [9]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [19]:
# Tensors to Tensors

x_ones = torch.ones_like(x_data)
print(f"One's Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype = torch.float)
print(f"Rand's Tensor: \n {x_rand} \n")

One's Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Rand's Tensor: 
 tensor([[0.4311, 0.1165],
        [0.7448, 0.6688]]) 



In [24]:
shape = (2,3)
rand_tensor = torch.rand(shape)
one_tensor = torch.ones(shape)
zero_tensor = torch.zeros(shape)

In [25]:
print(rand_tensor)
print(one_tensor)
print(zero_tensor)

tensor([[0.3254, 0.1522, 0.1884],
        [0.4401, 0.4143, 0.0136]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [27]:
print(f"Tensor is stored on: {one_tensor.device}")

Tensor is stored on: cpu


In [36]:
if torch.accelerator.is_available():
    rand_tensor = rand_tensor.to(torch.accelerator.current_accelerator())

In [41]:
tensor = torch.ones(4,4)
print(f"First row: {tensor[0,:]}")
print(f"Last column: {tensor[...,-1]}")

First row: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
